#!/bin/sh

# remove _CoqProject if it alreqdy exists
[ -e _CoqProject ] && rm _CoqProject

filt='^examples|^sandbox|^logic|^lang/ocaml|^lang/prog_notation'

echo "-arg -w
-arg -parsing
" >> _CoqProject

echo "# This file is automatically generated by configure.sh
# In order to prevent compilation of certain file, you can either comment them in the _CoqProject
# or you can use the egrep filter line 6: filt='...'

" >> _CoqProject

# generate the path for coqide and voqv
for D in $(find * -maxdepth 1 -type d | egrep -v $filt); do
	echo "-R $D Jasmin" | sed 's/\//./2'>> _CoqProject
done

echo "" >> _CoqProject

# generate the list of files for coq_makefile
# ls */*.v | egrep -v $filt >> _CoqProject
find * -name "*.v" -print | egrep -v $filt >> _CoqProject
 

# coq_makefile INSTALLDEFAULTROOT = Jasmin -f _CoqProject -o Makefile
# coq_makefile -f _CoqProject -o Makefile

